#!/bin/bash
set -e
GPU_ID=${1:-0}
export PYTHON=${PYTHON:-python}
echo ""
echo "======================================================================"
echo "  SafeCut  |  Run all datasets  |  GPU=${GPU_ID}"
echo "======================================================================"
echo ""
echo ">>> [1/4] Office-Home Start"
bash run_office_home.sh "${GPU_ID}"
echo "<<< [1/4] Office-Home Done"
echo ""
echo ">>> [2/4] Office-31 Start"
bash run_office31.sh "${GPU_ID}"
echo "<<< [2/4] Office-31 Done"
echo ""
echo ">>> [3/4] DomainNet-126 Start"
bash run_domainnet126.sh "${GPU_ID}"
echo "<<< [3/4] DomainNet-126 Done"
echo ""
echo ">>> [4/4] VisDA-C Start"
bash run_visda_c.sh "${GPU_ID}"
echo "<<< [4/4] VisDA-C Done"
echo ""
echo "======================================================================"
echo "  [All Done]  4 datasets completed"
echo "  Log location: outer_log/"
echo "======================================================================"
echo ""